// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJKROzUCkLpk_SudrQzHvllyF-U32Pmx4',
    appId: '1:649836945022:web:4b16caec04621bcf2b022f',
    messagingSenderId: '649836945022',
    projectId: 'e-library-952fa',
    authDomain: 'e-library-952fa.firebaseapp.com',
    storageBucket: 'e-library-952fa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXodXUjzNlCR9OqxEERyNltDbFHH4F3vQ',
    appId: '1:649836945022:android:4de4a4b3960d4fa62b022f',
    messagingSenderId: '649836945022',
    projectId: 'e-library-952fa',
    storageBucket: 'e-library-952fa.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJpWPpkBcJDfkhmQFmSvTcdaHNY46j6S4',
    appId: '1:649836945022:ios:b05ecc6eafbb50812b022f',
    messagingSenderId: '649836945022',
    projectId: 'e-library-952fa',
    storageBucket: 'e-library-952fa.appspot.com',
    iosClientId: '649836945022-1fh87dt7cdc6gm6suqcj5s5mbf4fo66m.apps.googleusercontent.com',
    iosBundleId: 'com.example.elibrary',
  );
}
